//! Port of `packages/zqlite/src/internal/sql-inline.ts`.
//!
//! Public exports ported:
//!
//! - [`compile_inline`] — given a SQL template string and a list of bound
//!   values, produces a SQL string with each value inlined as a SQL
//!   literal (except for `None` / undefined, which stays as `?`).
//! - [`inline_value`] — the value-to-literal encoder. Exposed for
//!   `sqlite_cost_model` callers (Layer 8c).
//! - [`escape_sqlite_string`] — doubles single quotes, wrapping in `'…'`.
//! - [`escape_sqlite_identifier`] — doubles double quotes, wrapping in
//!   `"…"`. Matches `@databases/escape-identifier::escapeSQLiteIdentifier`.
//!
//! ## TS model vs Rust model
//!
//! The TS function receives an `SQLQuery` object from the `@databases/sql`
//! template tag. That object already carries the SQL fragments and the
//! values separately. Our zqlite Rust port produces SQL via
//! [`crate::zqlite::query_builder`] as `(String, Vec<SqlValue>)` pairs
//! (inline `?` placeholders), so `compile_inline` here takes exactly that
//! shape: a template and a slice of `Option<&JsonValue>` values.
//!
//! The TS `formatValue` callback distinguishes `undefined` (emit `?` with
//! a binding) from all other values (emit the literal, no binding). In
//! Rust we model `undefined` as `None`. Callers that want a parameterised
//! query build the non-inline form via `compile` in a different module.
//!
//! ## Identifier length / Unicode validation
//!
//! The `@databases/escape-identifier` library enforces a 63-character
//! SQLite identifier limit and rejects non-ASCII. We do not replicate
//! those checks here: the callers (`query_builder`) already know the
//! identifier comes from a schema-discovered column/table name, and this
//! function is only used for cost-model SQL, not user-facing queries.

#![allow(dead_code)]

use serde_json::Value as JsonValue;

/// TS `escapeSQLiteString(str)`. Wraps `str` in single quotes, doubling
/// any single-quote inside.
pub fn escape_sqlite_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push('\'');
            out.push('\'');
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Port of `@databases/escape-identifier::escapeSQLiteIdentifier`. Wraps
/// `ident` in double quotes, doubling any embedded double quote.
pub fn escape_sqlite_identifier(ident: &str) -> String {
    if !ident.contains('"') {
        let mut out = String::with_capacity(ident.len() + 2);
        out.push('"');
        out.push_str(ident);
        out.push('"');
        return out;
    }
    let mut out = String::with_capacity(ident.len() + 4);
    out.push('"');
    for ch in ident.chars() {
        if ch == '"' {
            out.push('"');
            out.push('"');
        } else {
            out.push(ch);
        }
    }
    out.push('"');
    out
}

/// TS `inlineValue(value)`. Renders a JSON value as a SQL literal.
///
/// Branches:
/// - `None` / `Value::Null` → `NULL`
/// - string → `'…'` (single-quote doubled)
/// - number → numeric literal (f64 or i64 via `serde_json::Number` stringify)
/// - boolean → `1` / `0`
/// - array / object → JSON-stringified then wrapped as a string literal
pub fn inline_value(value: Option<&JsonValue>) -> String {
    // Branch: None (TS undefined path was handled by caller; for safety
    // we also render None → NULL).
    let Some(v) = value else {
        return "NULL".to_string();
    };
    match v {
        JsonValue::Null => "NULL".to_string(),
        JsonValue::String(s) => escape_sqlite_string(s),
        JsonValue::Number(n) => n.to_string(),
        JsonValue::Bool(b) => {
            if *b {
                "1".to_string()
            } else {
                "0".to_string()
            }
        }
        JsonValue::Array(_) | JsonValue::Object(_) => {
            // TS: `escapeSQLiteString(JSON.stringify(value))` for both
            // arrays and objects.
            escape_sqlite_string(&serde_json::to_string(v).unwrap_or_default())
        }
    }
}

/// TS `compileInline(sql)`.
///
/// Takes a SQL template with `?` placeholders and a slice of values.
/// Each `?` in order is replaced with the inlined literal produced by
/// [`inline_value`]. `None` values are preserved as `?` — TS's
/// `value === undefined` branch keeps the placeholder so the caller can
/// bind it later.
///
/// **Placeholder parsing.** TS uses the `@databases/sql` template to keep
/// literals and placeholders separate, so this is trivial. Here we scan
/// the template and replace each `?` that is not inside a string literal
/// or identifier. Since our template is machine-generated by
/// [`crate::zqlite::query_builder`] and never contains embedded `?`
/// characters inside literal strings, we keep the scanner simple: we skip
/// content between paired `'…'` (handling escaped `''`) and `"…"`
/// (handling escaped `""`) so user data that happens to contain a `?`
/// doesn't trip the replacement.
pub fn compile_inline(sql: &str, values: &[Option<JsonValue>]) -> String {
    let mut out = String::with_capacity(sql.len() + values.len() * 8);
    let bytes = sql.as_bytes();
    let mut i = 0usize;
    let mut v_idx = 0usize;
    while i < bytes.len() {
        let c = bytes[i];
        if c == b'\'' {
            // Copy string literal including the closing quote. SQLite
            // doubles `''` for an embedded quote, which we preserve.
            out.push('\'');
            i += 1;
            while i < bytes.len() {
                if bytes[i] == b'\'' {
                    out.push('\'');
                    i += 1;
                    // Embedded `''` — stay in literal.
                    if i < bytes.len() && bytes[i] == b'\'' {
                        out.push('\'');
                        i += 1;
                        continue;
                    }
                    break;
                }
                out.push(bytes[i] as char);
                i += 1;
            }
            continue;
        }
        if c == b'"' {
            out.push('"');
            i += 1;
            while i < bytes.len() {
                if bytes[i] == b'"' {
                    out.push('"');
                    i += 1;
                    if i < bytes.len() && bytes[i] == b'"' {
                        out.push('"');
                        i += 1;
                        continue;
                    }
                    break;
                }
                out.push(bytes[i] as char);
                i += 1;
            }
            continue;
        }
        if c == b'?' {
            // Branch: have a value to inline.
            if v_idx < values.len() {
                match &values[v_idx] {
                    None => out.push('?'),
                    some_val => out.push_str(&inline_value(some_val.as_ref())),
                }
                v_idx += 1;
                i += 1;
                continue;
            }
            // Branch: no value provided — leave ? as-is.
            out.push('?');
            i += 1;
            continue;
        }
        // Multi-byte UTF-8: push the whole char to stay valid.
        let ch_len = utf8_char_len(c);
        // Safety: we just read c, so bytes[i..i+ch_len] is a valid UTF-8 slice.
        out.push_str(std::str::from_utf8(&bytes[i..i + ch_len]).unwrap_or(""));
        i += ch_len;
    }
    out
}

fn utf8_char_len(first: u8) -> usize {
    if first < 0x80 {
        1
    } else if first < 0xC0 {
        1
    } else if first < 0xE0 {
        2
    } else if first < 0xF0 {
        3
    } else {
        4
    }
}

#[cfg(test)]
mod tests {
    //! Branch coverage:
    //! - `escape_sqlite_string` — no quotes, with single quote, empty.
    //! - `escape_sqlite_identifier` — no quotes, with double quote,
    //!   embedded quote doubling.
    //! - `inline_value` — Null, None, String, String with embedded quote,
    //!   Number (int & float), Bool true/false, Array, Object.
    //! - `compile_inline` — no placeholders; single `?`; multiple `?`;
    //!   `?` inside single-quoted literal is preserved; `?` inside
    //!   double-quoted identifier is preserved; `None` in values keeps
    //!   `?` unreplaced; fewer values than `?`s leaves remaining `?`s;
    //!   embedded `''` in string literal handled.

    use super::*;
    use serde_json::json;

    // Branch: escape_sqlite_string no quotes.
    #[test]
    fn escape_string_no_quote() {
        assert_eq!(escape_sqlite_string("hello"), "'hello'");
    }

    // Branch: escape_sqlite_string with single quote.
    #[test]
    fn escape_string_with_quote() {
        assert_eq!(escape_sqlite_string("it's"), "'it''s'");
    }

    // Branch: escape_sqlite_string empty.
    #[test]
    fn escape_string_empty() {
        assert_eq!(escape_sqlite_string(""), "''");
    }

    // Branch: escape_sqlite_identifier no special chars.
    #[test]
    fn escape_ident_simple() {
        assert_eq!(escape_sqlite_identifier("user"), "\"user\"");
    }

    // Branch: escape_sqlite_identifier with embedded double-quote.
    #[test]
    fn escape_ident_with_double_quote() {
        assert_eq!(escape_sqlite_identifier("we\"ird"), "\"we\"\"ird\"");
    }

    // Branch: inline_value for Null / None.
    #[test]
    fn inline_null() {
        assert_eq!(inline_value(None), "NULL");
        let v = JsonValue::Null;
        assert_eq!(inline_value(Some(&v)), "NULL");
    }

    // Branch: inline_value for string.
    #[test]
    fn inline_string() {
        let v = json!("hi");
        assert_eq!(inline_value(Some(&v)), "'hi'");
    }

    // Branch: inline_value for string with quote.
    #[test]
    fn inline_string_with_quote() {
        let v = json!("it's");
        assert_eq!(inline_value(Some(&v)), "'it''s'");
    }

    // Branch: inline_value for integer.
    #[test]
    fn inline_int() {
        let v = json!(42);
        assert_eq!(inline_value(Some(&v)), "42");
    }

    // Branch: inline_value for float.
    #[test]
    fn inline_float() {
        let v = json!(3.5);
        assert_eq!(inline_value(Some(&v)), "3.5");
    }

    // Branch: inline_value for boolean true/false.
    #[test]
    fn inline_bool() {
        assert_eq!(inline_value(Some(&json!(true))), "1");
        assert_eq!(inline_value(Some(&json!(false))), "0");
    }

    // Branch: inline_value for array → JSON string literal.
    #[test]
    fn inline_array() {
        let v = json!([1, 2, 3]);
        assert_eq!(inline_value(Some(&v)), "'[1,2,3]'");
    }

    // Branch: inline_value for object → JSON string literal.
    #[test]
    fn inline_object() {
        let v = json!({"a": 1});
        assert_eq!(inline_value(Some(&v)), "'{\"a\":1}'");
    }

    // Branch: compile_inline with no placeholders.
    #[test]
    fn compile_no_placeholders() {
        assert_eq!(compile_inline("SELECT 1", &[]), "SELECT 1");
    }

    // Branch: compile_inline single placeholder gets inlined.
    #[test]
    fn compile_single_placeholder() {
        let got = compile_inline("SELECT ? ", &[Some(json!(42))]);
        assert_eq!(got, "SELECT 42 ");
    }

    // Branch: multiple placeholders, in order.
    #[test]
    fn compile_multiple_placeholders() {
        let got = compile_inline("WHERE a=? AND b=?", &[Some(json!(1)), Some(json!("x"))]);
        assert_eq!(got, "WHERE a=1 AND b='x'");
    }

    // Branch: `?` inside string literal is preserved (not replaced).
    #[test]
    fn compile_question_mark_inside_string() {
        let got = compile_inline("SELECT '?'", &[]);
        assert_eq!(got, "SELECT '?'");
    }

    // Branch: `?` inside identifier is preserved.
    #[test]
    fn compile_question_mark_inside_identifier() {
        let got = compile_inline("SELECT \"?\" FROM t WHERE a=?", &[Some(json!(1))]);
        assert_eq!(got, "SELECT \"?\" FROM t WHERE a=1");
    }

    // Branch: None value leaves `?` in place.
    #[test]
    fn compile_none_keeps_placeholder() {
        let got = compile_inline("WHERE a=?", &[None]);
        assert_eq!(got, "WHERE a=?");
    }

    // Branch: fewer values than `?`s — trailing `?`s unreplaced.
    #[test]
    fn compile_fewer_values_than_placeholders() {
        let got = compile_inline("WHERE a=? AND b=?", &[Some(json!(1))]);
        assert_eq!(got, "WHERE a=1 AND b=?");
    }

    // Branch: embedded `''` in string literal.
    #[test]
    fn compile_doubled_quote_in_literal() {
        let got = compile_inline("SELECT 'it''s' FROM t WHERE a=?", &[Some(json!(1))]);
        assert_eq!(got, "SELECT 'it''s' FROM t WHERE a=1");
    }

    // Branch: embedded `""` in identifier.
    #[test]
    fn compile_doubled_quote_in_ident() {
        let got = compile_inline("\"we\"\"ird\" a=?", &[Some(json!(1))]);
        assert_eq!(got, "\"we\"\"ird\" a=1");
    }

    // -----------------------------------------------------------------
    // Golden fixtures: 5 byte-for-byte comparisons against the TS
    // `compileInline` output (captured via `scripts/dump-ts-sql.mjs`).
    // The TS implementation is the oracle.
    // -----------------------------------------------------------------

    #[test]
    fn golden_inline_a_no_params() {
        assert_eq!(compile_inline("SELECT 1", &[]), "SELECT 1");
    }

    #[test]
    fn golden_inline_b_single_string() {
        assert_eq!(
            compile_inline("SELECT ?", &[Some(json!("hi"))]),
            "SELECT 'hi'"
        );
    }

    #[test]
    fn golden_inline_c_single_number() {
        assert_eq!(compile_inline("SELECT ?", &[Some(json!(42))]), "SELECT 42");
    }

    #[test]
    fn golden_inline_d_multi_params() {
        assert_eq!(
            compile_inline("WHERE a=? AND b=?", &[Some(json!(1)), Some(json!("x"))]),
            "WHERE a=1 AND b='x'"
        );
    }

    #[test]
    fn golden_inline_e_mixed_types() {
        assert_eq!(
            compile_inline(
                "v=? b=? f=? n=?",
                &[
                    Some(json!(null)),
                    Some(json!(true)),
                    Some(json!(false)),
                    Some(json!(3.5)),
                ],
            ),
            "v=NULL b=1 f=0 n=3.5"
        );
    }
}
